version: '3.8'

services:
  thunderserver.api:
    image: ${DOCKER_REGISTRY-}thunderserverapi
    build:
      context: .
      dockerfile: ThunderServer/ThunderServer.API/Dockerfile
    depends_on:
      - db
    volumes:
      - C://TestFiles:/app/uploads:rw    
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: true

  thunderclient.webapp:
    image: ${DOCKER_REGISTRY-}thunderclientwebapp
    build:
      context: .
      dockerfile: ThunderClient/ThunderClient.WebApp/Dockerfile
    depends_on:
      - thunderserver.api

  db:
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: ThunderCloudServer
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: test