version: '3.4'

services:
  thunderserver.api:
    image: ${DOCKER_REGISTRY-}thunderserverapi
    build:
      context: .
      dockerfile: ThunderServer/ThunderServer.API/Dockerfile
    depends_on:
      - db
  

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: test
